[project]
name = "dota"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "dash>=4.0.0",
    "dash-mantine-components>=2.6.0",
    "httpx>=0.28.1",
    "ipykernel>=7.1.0",
    "jupyterlab>=4.5.2",
    "kagglehub>=1.0.0",
    "matplotlib>=3.10.8",
    "pandas>=2.3.3",
    "psycopg[binary]>=3.3.2",
    "python-dotenv>=1.2.1",
    "ratelimit>=2.2.1",
    "tenacity>=9.1.4",
]
